mail: Simplify fetching credentials
Signed-Off-By: scheatkode <scheatkode@disroot.org>

diff --git a/bin/secret-lookup b/bin/secret-lookup
--- a/bin/secret-lookup
+++ b/bin/secret-lookup
@@ -1,12 +1,25 @@
 #!/bin/sh
 
-# A helper that provides nicer syntax to git-credential-keepassxc for use in
-# scripts.
+# A wrapper for `git-credential-keepassxc` for a more user/script
+# friendly usage.
 
 set -e
 set -u
 
-partition_and_run() (
+has () {
+	command -v "${@}" >/dev/null 2>&1
+}
+
+prereq() {
+	if ! has git-credential-keepassxc; then
+		echo "error: git-credential-keepassxc dependency not found" 1>&2
+		exit 2 # ENOENT
+	fi
+}
+
+lookup () (
+	prereq
+
 	XDG_DATA_HOME="${XDG_DATA_HOME:-"${HOME}/.local/share"}"
 	CARGO_HOME="${CARGO_HOME:-"${XDG_DATA_HOME}/cargo"}"
 	PATH="${CARGO_HOME}/bin:${PATH}"
@@ -36,4 +49,4 @@ partition_and_run() (
 		| sed -n 's/^password=//p'
 )
 
-partition_and_run "${@}"
+lookup "${@}"
