fix(script): Fix dotfiles script
  - Convert : Tabs → Spaces
  - Fix     : Loops
  - Fix     : Arguments
  - Fix     : Unused variables
  - Fix     : Paths

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -1,4 +1,5 @@
 #!/bin/sh
+# shellcheck shell=sh
 
 # TODO:
 #   [ ] usage function
@@ -16,16 +17,15 @@ MAGENTA='\e[35m'
 
 # -- PATH INITIALIZATION ------------------------------------------------------
 
-user="${USER:-${LOGNAME:-#TODO}}"
 home="${HOME:-'~'}"
 
 
 # -- LOGGING FUNCTIONS --------------------------------------------------------
 
-info      () { echo -en    "${CYAN}[INFO]${NORMAL} " "${@} " ;          }
-infoline  () { echo -e     "${CYAN}[INFO]${NORMAL} " "${@} " ;          }
-warn      () { echo -e   "${YELLOW}[WARN]${NORMAL} " "${@} " ;          }
-fail      () { echo -e      "${RED}[FAIL]${NORMAL} " "${@} " ; exit 1 ; }
+info      () { echo -en    "${CYAN}[INFO]${NORMAL} " "${*} " ;          }
+infoline  () { echo -e     "${CYAN}[INFO]${NORMAL} " "${*} " ;          }
+warn      () { echo -e   "${YELLOW}[WARN]${NORMAL} " "${*} " ;          }
+fail      () { echo -e      "${RED}[FAIL]${NORMAL} " "${*} " ; exit 1 ; }
 success   () { echo -e  "\r${GREEN}[ OK ]${NORMAL}"          ;          }
 
 
@@ -34,17 +34,17 @@ success   () { echo -e  "\r${GREEN}[ OK ]${NORMAL}"          ;          }
 backup () {
     __ye_olde_IFS="${IFS}" ; IFS=','
 
-    for config in "${1}" ; do
-	case "${config}" in
-	    neovim) backup_neovim ;;
-	     emacs) backup_emacs  ;;
-	      tmux) backup_tmux   ;;
-	       all) backup_neovim
-		    backup_emacs
-		    backup_tmux
-		    ;;
-	         *) fail "Unknown configuration type '${config}'" ;;
-	    esac
+    for config in ${1} ; do
+        case "${config}" in
+            neovim) backup_neovim ;;
+             emacs) backup_emacs  ;;
+              tmux) backup_tmux   ;;
+               all) backup_neovim
+                    backup_emacs
+                    backup_tmux
+                    ;;
+                 *) fail "Unknown configuration type '${config}'" ;;
+            esac
     done
 
     IFS="${__ye_olde_IFS}"
@@ -55,8 +55,8 @@ backup_neovim () {
     info 'Backing up configuration for Neovim'
 
     if [ ! -d "${home}/.config/nvim" ] ; then
-	warn 'No configuration found for Neovim'
-	return 1
+        warn 'No configuration found for Neovim'
+        return 1
     fi
 
     mkdir -p "${home}/.config/backup/"
@@ -73,8 +73,8 @@ backup_emacs () {
     && [ ! -d "${home}/.emacs.d/"      ] \
     && [ ! -e "${home}/.emacs"         ] \
     ; then
-	warn 'No configuration found for Emacs'
-	return 1
+        warn 'No configuration found for Emacs'
+        return 1
     fi
 
     mkdir -p "${home}/.config/backup"
@@ -92,8 +92,8 @@ backup_tmux () {
     info 'Backing up configuration for tmux'
 
     if [ ! -e "${home}/.tmux.conf" ] ; then
-	warn 'No configuration found for tmux'
-	return 1
+        warn 'No configuration found for tmux'
+        return 1
     fi
 
     mkdir -p "${home}/.config/backup/"
@@ -108,17 +108,17 @@ backup_tmux () {
 restore () {
     __ye_olde_IFS="${IFS}" ; IFS=','
 
-    for config in "${1}" ; do
-	case "${config}" in
-	    neovim) restore_neovim ;;
-	     emacs) restore_emacs  ;;
-	      tmux) restore_tmux   ;;
-	       all) restore_neovim
-		    restore_emacs
-		    restore_tmux
-		    ;;
-	         *) fail "Unknown configuration type '${config}'" ;;
-	    esac
+    for config in ${1} ; do
+        case "${config}" in
+            neovim) restore_neovim ;;
+             emacs) restore_emacs  ;;
+              tmux) restore_tmux   ;;
+               all) restore_neovim
+                    restore_emacs
+                    restore_tmux
+                    ;;
+                 *) fail "Unknown configuration type '${config}'" ;;
+            esac
     done
 
     IFS="${__ye_olde_IFS}"
@@ -129,8 +129,8 @@ restore_neovim () {
     info 'Restoring configuration for Neovim'
 
     if [ ! -d "${home}/.config/backup/nvim/" ] ; then
-	warn 'No backup found for Neovim'
-	return 1
+        warn 'No backup found for Neovim'
+        return 1
     fi
 
     mv "${home}/.config/backup/nvim/" "${home}/.config/"
@@ -146,8 +146,8 @@ restore_emacs () {
     && [ ! -d "${home}/.config/backup/.emacs.d/" ] \
     && [ ! -e "${home}/.config/backup/.emacs"    ] \
     ; then
-	warn 'No backup found for Emacs'
-	return 1
+        warn 'No backup found for Emacs'
+        return 1
     fi
 
     mv "${home}/.config/backup/emacs/"   "${home}/.config/" 2> /dev/null
@@ -162,8 +162,8 @@ restore_tmux () {
     info 'Restoring configuration for tmux'
 
     if [ ! -e "${home}/.config/backup/.tmux.conf" ] ; then
-	warn 'No backup found for tmux'
-	return 1
+        warn 'No backup found for tmux'
+        return 1
     fi
 
     mv "${home}/.config/backup/.tmux.conf" "${home}/"
@@ -177,17 +177,17 @@ restore_tmux () {
 install () {
     __ye_olde_IFS="${IFS}" ; IFS=','
 
-    for config in "${1}" ; do
-	case "${config}" in
-	    neovim) install_neovim ;;
-	     emacs) install_emacs  ;;
-	      tmux) install_tmux   ;;
-	       all) install_neovim
-		    install_emacs
-		    install_tmux
-		    ;;
-	         *) fail "Unknown configuration type '${config}'" ;;
-	    esac
+    for config in ${1} ; do
+        case "${config}" in
+            neovim) install_neovim ;;
+             emacs) install_emacs  ;;
+              tmux) install_tmux   ;;
+               all) install_neovim
+                    install_emacs
+                    install_tmux
+                    ;;
+                 *) fail "Unknown configuration type '${config}'" ;;
+            esac
     done
 
     IFS="${__ye_olde_IFS}"
@@ -198,8 +198,8 @@ install_neovim () {
     backup_neovim
 
     info 'Installing Neovim configuration'
-    ln -s "`pwd`/neovim/" "${home}/.config/nvim" \
-	|| fail 'Unable to install tmux'
+    ln -s "`pwd`/src/neovim/" "${home}/.config/nvim" \
+        || fail 'Unable to install tmux'
     success
 }
 
@@ -208,8 +208,8 @@ install_emacs () {
     backup_emacs
 
     info 'Installing Emacs configuration'
-    ln -s "`pwd`/emacs" "${home}/.config/emacs" \
-	|| fail 'Unable to install tmux'
+    ln -s "`pwd`/src/emacs/" "${home}/.config/emacs" \
+        || fail 'Unable to install tmux'
     success
 }
 
@@ -218,8 +218,8 @@ install_tmux () {
     backup_tmux
 
     info 'Installing tmux configuration'
-    ln -s "`pwd`/tmux.conf" "${home}/.tmux.conf" \
-	|| fail 'Unable to install tmux'
+    ln -s "`pwd`/src/tmux/tmux.conf" "${home}/.tmux.conf" \
+        || fail 'Unable to install tmux'
     success
 }
 
@@ -235,8 +235,8 @@ usage () {
 
     install [program]   Install the program configuration
     restore [program]   Restore the program's previously backed up configuration
-    backup  [program]	Backup the program's configuration
-    help    		Show this help screen
+    backup  [program]   Backup the program's configuration
+    help                Show this help screen
 
   Supported programs:
 
@@ -251,9 +251,9 @@ EOF
 
 main () {
     case "$#" in
-	1) ;;
-	2) ;;
-	*) fail 'Wrong number of parameters'
+        1) ;;
+        2) ;;
+        *) fail 'Wrong number of parameters'
     esac
 
     case "${1}" in
@@ -267,6 +267,7 @@ main () {
 
 if [ x"$0" = x"./dotfiles" ] ; then main "${@}" ; fi
 
+# -- EDITOR MODES -------------------------------------------------------------
 # vim: ft=sh
 #
 # Local Variables:
